### PR TITLE
Integration is working locally with a basic contract pair

### PR DESCRIPTION
**Pull request by rzaracota**
We have a lot of separate pieces. Now is the time to put them together. I have done what I think is our current plan and merged Nav's demo with my http client to pull from the backend api successfully. I would like to make some more progress on this before merging but I believe it is where our continued effort should be focused.

In particular, the data contract is not completely agreed upon so it may break, however, the basic infrastructure is in place so it should be a matter of simple changes to the contract in the service client and frontend spruce up to get a decent site going.

The site can be run from 'Software Management Course Website' project and click on modules for the the most recent changes.

### CODE REVIEW

**Comment by rzaracota** [comment]
I confirmed this also works with the public endpoint http://css566backend.azurewebsites.net

**Comment by mitchl2** [comment]
Is the  'Software Management Course Website' website set up to pull from the /module & /course APIs?

**Comment by rzaracota** [comment]
Yes it was working with the published api /courses and /modules for me

**Comment by mitchl2** [comment]
Ok, thank you

**Pull request merged**
